name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-assignment:
    name: Run Assignment Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make libgtest-dev python3-pip

      - name: Run Lint
        run: ./scripts/lint.sh "SWB-04"

      - name: Run Build and Tests via Makefile
        run: ./scripts/build.sh "SWB-04"